=== 등록 (register)

==== 명세

operation::Auth/Register/ok[snippets='http-request,request-fields']

==== 성공

operation::Auth/Register/ok[snippets='http-response']

==== 실패

operation::Auth/Register/duplicated[snippets='http-response']

IMPORTANT: 유저가 이미 존재할 때

operation::Auth/Register/wrongFormatDto[snippets='http-response']

IMPORTANT: Payload값이 적절하지 않음

=== 로그인 (login)

==== 명세

operation::Auth/Login/ok[snippets='http-request,request-fields']

==== 성공

operation::Auth/Login/ok[snippets='http-response']

===== 실패

operation::Auth/Login/wrongPassword[snippets='http-response']

IMPORTANT: 비밀번호가 잘못되었을 때

operation::Auth/Login/notRegistered[snippets='http-response']

IMPORTANT: 유저를 찾을 수 없을 때

operation::Auth/Login/wrongFormat[snippets='http-response']

IMPORTANT: Payload 값이 적절하지 않음

=== 리프레시 토큰 (refresh)

==== 명세

operation::Auth/Refresh/ok[snippets='http-request']

==== 성공

operation::Auth/Refresh/ok[snippets='http-response']

==== 실패

operation::Auth/Refresh/wrongToken[snippets='http-response']

IMPORTANT: refresh 토큰이 잘못되었을 때

=== 특권 유저 변경 (elevate)

==== 명세

operation::Auth/Elevate/ok[snippets='http-request']

==== 성공

operation::Auth/Elevate/ok[snippets='http-response']

==== 실패

operation::Auth/Elevate/wrongPassword[snippets='http-response']

IMPORTANT: 잘못된 pssword를 보냈을 때

operation::Auth/Elevate/wrongToken[snippets='http-response']

IMPORTANT: 로그인토큰이 잘못되었을 때

=== 유저 삭제 (deregister)

==== 명세

operation::Auth/Deregister/ok[snippets='http-request']

==== 성공

operation::Auth/Deregister/ok[snippets='http-response']

==== 실패

operation::Auth/Deregister/notPrivilege[snippets='http-response']

IMPORTANT: 권한이 없을 때

=== 특권 유저 확인 (privileged)

==== 명세

operation::Auth/Privileged/ok[snippets='http-request']

==== 성공

operation::Auth/Privileged/ok[snippets='http-response']

IMPORTANT: 유저가 특권유저일 때

operation::Auth/Privileged/notPrivilege[snippets='http-response']

IMPORTANT: 유저가 특권유저가 아닐 때

=== 관리자 유저 확인 (admin-check)

==== 명세

operation::Auth/AdminCheck/ok[snippets='http-request']

==== 성공

operation::Auth/AdminCheck/ok[snippets='http-response']

IMPORTANT: 유저가 관리자일 때

operation::Auth/AdminCheck/notPrivilege[snippets='http-response']

IMPORTANT: 유저가 관리자가 아닐 때
