version: '3.8'

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: pw
      MARIADB_DATABASE: test_db
      MARIADB_USER: myuser
      MARIADB_PASSWORD: mypassword
      MYSQL_TCP_PORT: 3333
    expose:
      - "3333"
    volumes:
      - ./data:/var/lib/mysql
    container_name: mariadb
  spring:
     image: small_cloud
     build: .
     ports:
      - "8000:8000"
     depends_on:
      - db
     container_name: backend
