version: '3.8'

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${SMALLCLOUD_DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${SMALLCLOUD_DB_DATABASE}
      MARIADB_USER: ${SMALLCLOUD_DB_USERNAME}
      MARIADB_PASSWORD: ${SMALLCLOUD_DB_PASSWORD}
      MYSQL_TCP_PORT: ${SMALLCLOUD_DB_PORT}
      MYSQL_UNIX_PORT: ${SMALLCLOUD_DB_PORT}
    expose:
      - ${SMALLCLOUD_DB_PORT}
    volumes:
      - ./db/ddl:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "--silent", "-h", "localhost", "-u", "root", "-p${SMALLCLOUD_DB_ROOT_PASSWORD}" ]
      timeout: 20s
      retries: 10

  spring:
    image: small_cloud
    restart: always
    build: backend
    ports:
      - "${SMALLCLOUD_BACKEND_PORT}:${SMALLCLOUD_BACKEND_PORT}"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      - TZ=Asia/Seoul

  react:
    image: small_cloud_front
    restart: always
    build: frontend
    ports:
      - "${SMALLCLOUD_FRONTEND_PORT}:${SMALLCLOUD_FRONTEND_PORT}"
    depends_on:
      - spring

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":${SMALLCLOUD_MINIO_ADMIN_PORT}"
    restart: always
    environment:
      MINIO_ROOT_USER: ${SMALLCLOUD_MINIO_USER}
      MINIO_ROOT_PASSWORD: ${SMALLCLOUD_MINIO_PASSWORD}
    ports:
      - "${SMALLCLOUD_MINIO_PORT}:${SMALLCLOUD_MINIO_PORT}"
      - "${SMALLCLOUD_MINIO_ADMIN_PORT}:${SMALLCLOUD_MINIO_ADMIN_PORT}"
    volumes:
      - ./minio:/data
