spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3333/test_db?serverTimezone=Asia/Seoul
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true