spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://db:3333/test_db?serverTimezone=Asia/Seoul
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MariaDB103Dialect

jwt:
  secret: U29tdGhpbmdTcGVjaWFsU21hbGxDbG91ZCMkIV4lKiU
