spring:
  profiles:
    default: local
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true

jwt:
  secret: U29tdGhpbmdTcGVjaWFsU21hbGxDbG91ZCMkIV4lKiU
