spring:
  profiles:
    default: local
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true

jwt:
  secret: U29tdGhpbmdTcGVjaWFsU21hbGxDbG91ZCMkIV4lKiU

minio:
  url: http://minio:9000
  user: minio
  password: miniopass
  bucket-name: scloud

external:
  front_origin: "http://121.155.7.179:3000"
  local_origin: "http://localhost:3000"

server:
  port: 8000
