= SmallCloud API 명세
:toc: left
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toclevels: 2
:sectlinks:
// :sectnums: // 분류별 자동으로 숫자를 달아줌
// :docinfo: shared-head

[[overview]]
== 인증 관련 (auth)

=== 등록 (register)

==== 명세

operation::Register[snippets='http-request,request-fields']

==== 성공

operation::Register[snippets='http-response']

==== 실패

operation::RegisterFail[snippets='http-response']

IMPORTANT: 유저가 이미 존재할 때

=== 로그인 (login)

==== 명세

operation::Login[snippets='http-request,request-fields']

==== 성공

operation::Login[snippets='http-response']

===== 실패

operation::WrongPassword[snippets='http-response']

IMPORTANT: 비밀번호가 잘못되었을 때

operation::NotFoundUserLogin[snippets='http-response']

IMPORTANT: 유저를 찾을 수 없을 때

=== 리프레시 토큰 (refresh)

==== 명세

operation::Refresh[snippets='http-request']

==== 성공

operation::Refresh[snippets='http-response']

==== 실패

operation::RefreshBadToken[snippets='http-response']

IMPORTANT: refresh 토큰이 잘못되었을 때

=== 특권 유저 변경 (elevate)

==== 명세

operation::Elevate[snippets='http-request']

==== 성공

operation::Elevate[snippets='http-response']

==== 실패

operation::ElevateWrongPassword[snippets='http-response']

IMPORTANT: 잘못된 pssword를 보냈을 때

operation::ElevateUnauth[snippets='http-response']

IMPORTANT: 로그인토큰이 잘못되었을 때

=== 유저 삭제 (deregister)

==== 명세

operation::Deregister[snippets='http-request']

==== 성공

operation::Deregister[snippets='http-response']

==== 실패

operation::DeregisterPrivilege[snippets='http-response']

IMPORTANT: 권한이 없을 때

=== 유저 삭제 (deregister)

==== 명세

operation::Privileged[snippets='http-request']

==== 성공

operation::Privileged[snippets='http-response']

IMPORTANT: 유저가 특권유저일 때

operation::PrivilegedFalse[snippets='http-response']

IMPORTANT: 유저가 특권유저가 아닐 때
