= SmallCloud API 명세
:toc: left
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toclevels: 2
:sectlinks:
// :sectnums: // 분류별 자동으로 숫자를 달아줌
// :docinfo: shared-head

[[overview]]
== 인증 관련 (auth)

=== 등록 (register)

==== 명세

operation::Register[snippets='http-request,request-fields']

==== 성공

operation::Register[snippets='http-response']

==== 실패

operation::RegisterFail[snippets='http-response']

IMPORTANT: 유저가 이미 존재할 때

operation::RegisterWrongFormat[snippets='http-response']

IMPORTANT: Payload값이 적절하지 않음

=== 로그인 (login)

==== 명세

operation::Login[snippets='http-request,request-fields']

==== 성공

operation::Login[snippets='http-response']

===== 실패

operation::WrongPassword[snippets='http-response']

IMPORTANT: 비밀번호가 잘못되었을 때

operation::NotFoundUserLogin[snippets='http-response']

IMPORTANT: 유저를 찾을 수 없을 때

operation::NotValidLogin[snippets='http-response']

IMPORTANT: Payload 값이 적절하지 않음

=== 리프레시 토큰 (refresh)

==== 명세

operation::Refresh[snippets='http-request']

==== 성공

operation::Refresh[snippets='http-response']

==== 실패

operation::RefreshBadToken[snippets='http-response']

IMPORTANT: refresh 토큰이 잘못되었을 때

=== 특권 유저 변경 (elevate)

==== 명세

operation::Elevate[snippets='http-request']

==== 성공

operation::Elevate[snippets='http-response']

==== 실패

operation::ElevateWrongPassword[snippets='http-response']

IMPORTANT: 잘못된 pssword를 보냈을 때

operation::ElevateUnauth[snippets='http-response']

IMPORTANT: 로그인토큰이 잘못되었을 때

=== 유저 삭제 (deregister)

==== 명세

operation::Deregister[snippets='http-request']

==== 성공

operation::Deregister[snippets='http-response']

==== 실패

operation::DeregisterPrivilege[snippets='http-response']

IMPORTANT: 권한이 없을 때

=== 특권 유저 확인 (privileged)

==== 명세

operation::Privileged[snippets='http-request']

==== 성공

operation::Privileged[snippets='http-response']

IMPORTANT: 유저가 특권유저일 때

operation::PrivilegedFalse[snippets='http-response']

IMPORTANT: 유저가 특권유저가 아닐 때

== 유저 관련 (users)

=== 삭제 (delete)

operation::UserDelete[snippets='http-request,path-parameters']

==== 성공

operation::UserDelete[snippets='http-response']

==== 실패

operation::UserDeleteUsernameToLong[snippets='http-response']

IMPORTANT: 아이디가 너무 길 때

operation::UserDeleteNotUser[snippets='http-response']

IMPORTANT: 등록되지 않은 유저일 때

operation::UserDeleteUnauthorized[snippets='http-response']

IMPORTANT: 권한이 없을 때

=== 등록 (register)

operation::UserRegister[snippets='http-request,request-fields']

==== 성공

operation::UserRegister[snippets='http-response']

==== 실패

operation::UserRegisterUnauthorized[snippets='http-response']

IMPORTANT: 권한이 없을 때

operation::UserRegisterWrongFormat[snippets='http-response']

IMPORTANT: payload가 올바르지 않을 때

operation::UserRegisterDuplicated[snippets='http-response']

IMPORTANT: 중복된 유저 등록

=== 프로필 업데이트 (update)

operation::UserUpdate[snippets='http-request,request-fields,path-parameters']

==== 성공

operation::UserUpdate[snippets='http-response']

==== 실패

operation::UserUpdateUnauthorized[snippets='http-response']

IMPORTANT: 권한이 없을 때

operation::UserUpdateWrongFormat[snippets='http-response']

IMPORTANT: payload가 올바르지 않을 때

operation::UserUpdateNotFoundUser[snippets='http-response']

IMPORTANT: 유저를 찾을 수 없을 때

operation::UserUpdateDuplicated[snippets='http-response']

IMPORTANT: 중복된 유저 등록

operation::UserUpdateNotFound[snippets='http-response']

IMPORTANT: 그룹을 찾을 수 없을 때

=== 프로필 조회 (profile)

operation::UserProfile[snippets='http-request,path-parameters']

==== 성공

operation::UserProfile[snippets='http-response']

==== 실패

operation::UserProfileUnauthorized[snippets='http-response']

IMPORTANT: 권한이 없을 때

operation::UserProfileNotFoundUser[snippets='http-response']

IMPORTANT: 유저를 찾을 수 없을 때

operation::UserProfileNotValidUser[snippets='http-response']

IMPORTANT: 유저 아이디가 유효하지 않을 때
