spring:
  servlet:
    multipart:
      max-file-size: 100GB
      max-request-size: 100GB
  profiles:
    default: local
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true

jwt:
  secret: U29tdGhpbmdTcGVjaWFsU21hbGxDbG91ZCMkIV4lKiU

external:
  front_origin: "http://121.155.7.179:3000"
  local_origin: "http://localhost:3000"

server:
  port: 8000
  address: 0.0.0.0
