spring:
  profiles:
    default: local
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true

jwt:
  secret: { SMALLCLOUD_SECRET }

external:
  origin: { SMALLCLOUD_ORIGIN }

server:
  port: { SMALLCLOUD_BACKEND_PORT }
  address: { SMALLCLOUD_ADDRESS }

smallcloud:
  admin:
    username: { SMALLCLOUD_ADMIN_USERNAME }
    password: { SMALLCLOUD_ADMIN_PASSWORD }
