spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: false

logging:
  call-tracer: true
  level:
    org.mint.smallcloud: debug

external:
  origin: "http://localhost:3000"

jwt:
  secret: 3141ffdaff9626f76648ce729d0817617c5531d73fe4ec3a5727ae773106da09

server:
  port: 8000
  address: 0.0.0.0
  front-port: 3000


smallcloud:
  admin:
    username: test
    password: test
