=== 등록 (create)

==== 명세

operation::Directory/Create/ok[snippets='http-request,request-fields,path-parameters']

==== 성공

operation::Directory/Create/ok[snippets='http-response']

==== 실패

operation::Directory/Create/parentNotFound[snippets='http-response']

IMPORTANT: 부모 디렉토리가 존재하지 않는 경우

operation::Directory/Create/noToken[snippets='http-response']

IMPORTANT: 토큰이 없는 경우

operation::Directory/Create/noAccessRight[snippets='http-response']

IMPORTANT: 접근 권한이 없는 경우

=== 이름 바꾸기 (rename)

==== 명세

operation::Directory/Rename/ok[snippets='http-request,request-fields,path-parameters']

==== 성공

operation::Directory/Rename/ok[snippets='http-response']

==== 실패

operation::Directory/Rename/parentNotFound[snippets='http-response']

IMPORTANT: 부모 디렉토리가 존재하지 않는 경우

operation::Directory/Rename/noToken[snippets='http-response']

IMPORTANT: 토큰이 없는 경우

operation::Directory/Rename/noAccessRight[snippets='http-response']

IMPORTANT: 접근 권한이 없는 경우

=== 이동 (move)

==== 명세

operation::Directory/Move/ok[snippets='http-request,request-fields,path-parameters']

==== 성공

operation::Directory/Move/ok[snippets='http-response']

=== 정보 (info)

==== 명세

operation::Directory/Info/ok[snippets='http-request,path-parameters']

==== 성공

operation::Directory/Info/ok[snippets='http-response']

=== 자식 폴더 (subDirectories)

==== 명세

operation::Directory/SubDirectories/ok[snippets='http-request,path-parameters']

==== 성공

operation::Directory/SubDirectories/ok[snippets='http-response']

=== 자식 파일 (subFiles)

==== 명세

operation::Directory/Files/ok[snippets='http-request,path-parameters']

==== 성공

operation::Directory/Files/ok[snippets='http-response']

=== 완전삭제 (purge)

operation::Directory/Purge/ok[snippets='http-request,path-parameters']

==== 성공

operation::Directory/Purge/ok[snippets='http-response']

=== 삭제 (delete)

operation::Directory/Delete/ok[snippets='http-request,path-parameters']

==== 성공

operation::Directory/Delete/ok[snippets='http-response']

=== 복구 (restore)

operation::Directory/Restore/ok[snippets='http-request,path-parameters']

==== 성공

operation::Directory/Restore/ok[snippets='http-response']

=== 즐겨찾기 추가 (favorite)

operation::Directory/favorite/ok[snippets='http-request,path-parameters']

==== 성공

operation::Directory/favorite/ok[snippets='http-response']

IMPORTANT: 어떤 라벨도 붙어있지 않을 때

operation::Directory/favorite/okLabel[snippets='http-response']

IMPORTANT: 다른 라벨이 붙어있을 때

=== 즐겨찾기 삭제 (unfavorite)

operation::Directory/unFavorite/ok[snippets='http-request,path-parameters']

==== 성공

operation::Directory/unFavorite/ok[snippets='http-response']

IMPORTANT: 즐겨찾기 라벨만 붙어있을 때

operation::Directory/unFavorite/okOther[snippets='http-response']

IMPORTANT: 다른 라벨이 붙어있을 때

=== 폴더 검색

operation::Directory/search/ok[snippets='http-request,request-parameters']

==== 성공

operation::Directory/search/ok[snippets='http-response']




