=== 등록 (create)

==== 명세

operation::Directory/Create/ok[snippets='request-fields,path-parameters']

==== 성공

operation::Directory/Create/ok[snippets='http-response']

==== 실패

operation::Directory/Create/parentNotFound[snippets='http-response']

IMPORTANT:부모 디렉토리가 존재하지 않는 경우

operation::Directory/Create/noToken[snippets='http-response']

IMPORTANT:토큰이 없는 경우

operation::Directory/Create/noAccessRight[snippets='http-response']

IMPORTANT:접근 권한이 없는 경우

=== 이름 바꾸기 (rename)

==== 명세

operation::Directory/Rename/ok[snippets='request-fields,path-parameters']

==== 성공

operation::Directory/Rename/ok[snippets='http-response']

==== 실패

operation::Directory/Rename/parentNotFound[snippets='http-response']

IMPORTANT:부모 디렉토리가 존재하지 않는 경우

operation::Directory/Rename/noToken[snippets='http-response']

IMPORTANT:토큰이 없는 경우

operation::Directory/Rename/noAccessRight[snippets='http-response']

IMPORTANT:접근 권한이 없는 경우

=== 이동 (move)

==== 명세

operation::Directory/Move/ok[snippets='request-fields,path-parameters']

==== 성공

operation::Directory/Move/ok[snippets='http-response']