=== 파일 라벨 업데이트 (labelUpdate)

operation::file/labelUpdate/okNoLabels[snippets='http-request']

==== 성공

operation::file/labelUpdate/okNoLabels[snippets='http-response']

IMPORTANT: 파일에 라벨이 하나도 붙어있지 않을 때

operation::file/labelUpdate/okSomeLabels[snippets='http-response']

IMPORTANT: 파일에 라벨이 일부 붙어있을 때

==== 실패

operation::file/labelUpdate/noFile[snippets='http-response']

IMPORTANT: 파일이 없을 때

operation::file/labelUpdate/wrongToken[snippets='http-response']

IMPORTANT: 잘못된 토큰

=== 파일 삭제 (delete)

operation::file/delete/okNoLabel[snippets='http-request,path-parameters']

==== 성공

operation::file/delete/okNoLabel[snippets='http-response']

IMPORTANT: 파일에 라벨이 하나도 붙어있지 않을 때

operation::file/delete/okLabel[snippets='http-response']

IMPORTANT: 파일에 라벨이 붙어있을 때

==== 실패

operation::file/delete/existLabel[snippets='http-response']

IMPORTANT: 파일에 휴지통 라벨이 붙어있을 때

operation::file/delete/noFile[snippets='http-response']

IMPORTANT: 파일이 없을 때

operation::file/delete/wrongToken[snippets='http-response']

IMPORTANT: 잘못된 토큰

=== 파일 복구 (restore)

operation::file/restore/okNoLabel[snippets='http-request,path-parameters']

==== 성공

operation::file/restore/ok[snippets='http-response']

IMPORTANT: 복구 시 파일에 휴지통 라벨만 붙어 있을 때

operation::file/restore/okOther[snippets='http-response']

IMPORTANT: 복구 시 파일에 휴지통 라벨과 다른 라벨이 붙어 있을 때

==== 실패

operation::file/restore/noLabels[snippets='http-response']

IMPORTANT: 파일에 라벨이 하나도 붙어 있지 않을 때

operation::file/restore/noTrash[snippets='http-response']

IMPORTANT: 파일에 휴지통 라벨이 붙어 있지 않을 때

operation::file/restore/noFile[snippets='http-response']

IMPORTANT: 파일이 없을 때

operation::file/restore/wrongToken[snippets='http-response']

IMPORTANT: 잘못된 토큰

=== 파일 이동 (move)

operation::file/move/ok[snippets='http-request,request-fields,path-parameters']

==== 성공

operation::file/move/ok[snippets='http-response']

IMPORTANT: 정상 요청

operation::file/move/fileNotFound[snippets='http-response']

IMPORTANT: 파일이 없을 때

operation::file/move/destNotFound[snippets='http-response']

IMPORTANT: 이동할 폴더가 없을 때

operation::file/move/noAccessRight[snippets='http-response']

IMPORTANT: 권한이 없을 때

=== 파일 완전 삭제 (purge)

operation::file/purge/ok[snippets='http-request,path-parameters']

==== 성공

operation::file/purge/ok[snippets='http-response']

=== 즐겨찾기 추가 (favorite)

operation::file/favorite/okNoLabel[snippets='http-request,path-parameters']

==== 성공

operation::file/favorite/okNoLabel[snippets='http-response']

IMPORTANT: 파일에 라벨이 하나도 붙어있지 않을 때

operation::file/favorite/okLabel[snippets='http-response']

IMPORTANT: 파일에 라벨이 붙어있을 때

==== 실패

operation::file/favorite/existLabel[snippets='http-response']

IMPORTANT: 파일에 즐겨찾기 라벨이 붙어있을 때

operation::file/favorite/noFile[snippets='http-response']

IMPORTANT: 파일이 없을 때

operation::file/favorite/wrongToken[snippets='http-response']

IMPORTANT: 잘못된 토큰

=== 즐겨찾기 삭제 (unfavorite)

operation::file/unFavorite/ok[snippets='http-request,path-parameters']

==== 성공

operation::file/unFavorite/ok[snippets='http-response']

IMPORTANT: 파일에 즐겨찾기 라벨만 붙어 있을 때

operation::file/unFavorite/okOther[snippets='http-response']

IMPORTANT: 파일에 즐겨찾기 라벨과 다른 라벨이 붙어 있을 때

==== 실패

operation::file/unFavorite/noLabels[snippets='http-response']

IMPORTANT: 파일에 라벨이 하나도 붙어 있지 않을 때

operation::file/unFavorite/noFavorite[snippets='http-response']

IMPORTANT: 파일에 즐겨찾기 라벨이 붙어 있지 않을 때

operation::file/unFavorite/noFile[snippets='http-response']

IMPORTANT: 파일이 없을 때

operation::file/unFavorite/wrongToken[snippets='http-response']

IMPORTANT: 잘못된 토큰

=== 파일 검색

operation::file/search/ok[snippets='http-request,request-parameters']

==== 성공

operation::file/search/ok[snippets='http-response']


