=== 파일 라벨 업데이트 (labelUpdate)

operation::file/labelUpdate/okNoLabels[snippets='http-request']

==== 성공

operation::file/labelUpdate/okNoLabels[snippets='http-response']

IMPORTANT: 파일에 라벨이 하나도 붙어있지 않을 때

operation::file/labelUpdate/okSomeLabels[snippets='http-response']

IMPORTANT: 파일에 라벨이 일부 붙어있을 때

==== 실패

operation::file/labelUpdate/noFile[snippets='http-response']

IMPORTANT: 파일이 없을 때

operation::file/labelUpdate/wrongToken[snippets='http-response']

IMPORTANT: 잘못된 토큰

=== 파일 삭제 (delete)

operation::file/delete/okNoLabel[snippets='http-request,path-parameters']

==== 성공

operation::file/delete/okNoLabel[snippets='http-response']

IMPORTANT: 파일에 라벨이 하나도 붙어있지 않을 때

operation::file/delete/okLabel[snippets='http-response']

IMPORTANT: 파일에 라벨이 붙어있을 때

==== 실패

operation::file/delete/existLabel[snippets='http-response']

IMPORTANT: 파일에 휴지통 라벨이 붙어있을 때

operation::file/delete/noFile[snippets='http-response']

IMPORTANT: 파일이 없을 때

operation::file/delete/wrongToken[snippets='http-response']

IMPORTANT: 잘못된 토큰

=== 파일 복구 (restore)

operation::file/restore/okNoLabel[snippets='http-request,path-parameters']

==== 성공

operation::file/restore/ok[snippets='http-response']

IMPORTANT: 복구 시 파일에 휴지통 라벨만 붙어 있을 때

operation::file/restore/okOther[snippets='http-response']

IMPORTANT: 복구 시 파일에 휴지통 라벨과 다른 라벨이 붙어 있을 때

==== 실패

operation::file/restore/noLabels[snippets='http-response']

IMPORTANT: 파일에 라벨이 하나도 붙어 있지 않을 때

operation::file/restore/noTrash[snippets='http-response']

IMPORTANT: 파일에 휴지통 라벨이 붙어 있지 않을 때

operation::file/restore/noFile[snippets='http-response']

IMPORTANT: 파일이 없을 때

operation::file/restore/wrongToken[snippets='http-response']

IMPORTANT: 잘못된 토큰

=== 파일 이동 (move)

operation::file/Move/ok[snippets='http-request,request-fields,path-parameters']

==== 성공

operation::file/Move/ok[snippets='http-response']

IMPORTANT: 정상 요청

operation::file/Move/fileNotFound[snippets='http-response']

IMPORTANT: 파일이 없을 때

operation::file/Move/destNotFound[snippets='http-response']

IMPORTANT: 이동할 폴더가 없을 때

operation::file/Move/noAccessRight[snippets='http-response']

IMPORTANT: 권한이 없을 때