=== 문의 등록

operation::Board/Save/okOneToOne[snippets='http-request,request-fields']

==== 성공

operation::Board/Save/okOneToOne[snippets='http-response']

IMPORTANT: 로그인 하고 요청

operation::Board/Save/okLogin[snippets='http-response']

IMPORTANT: 로그인 안하고 요청

==== 실패

operation::Board/Save/wrongToken[snippets='http-response']

IMPORTANT: 연락처가 없을 때

operation::Board/Save/wrongToken[snippets='http-response']

IMPORTANT: 토큰이 잘못되었을 때

=== 문의 전체 조회

operation::Board/GetInquiries/ok[snippets='http-request']

==== 성공

operation::Board/GetInquiries/ok[snippets='http-response']

=== 선택

operation::Board/select/ok[snippets='http-request,path-parameters']

==== 성공

operation::Board/select/ok[snippets='http-response']

==== 실패

operation::Board/select/wrongSelect[snippets='http-response']

IMPORTANT: 잘못된 문의 선택 조회

operation::Board/select/wrongSelect[snippets='http-response']

IMPORTANT: 토큰이 잘못됨

=== 답변 등록

operation::Board/answer/okOneToOneAnswer[snippets='http-request']

==== 성공

operation::Board/answer/okOneToOneAnswer[snippets='http-response']

IMPORTANT: 1:1 문의 상황일 때

operation::Board/answer/okLoginAnswer[snippets='http-response']

IMPORTANT: 로그인 문의 상황일 때

==== 실패

operation::Board/answer/noContent[snippets='http-response']

IMPORTANT: 답변 내용이 없을 때

operation::Board/answer/wrongToken[snippets='http-response']

IMPORTANT: 토큰이 잘못됨

=== 답변 되지 않은 문의 조회

operation::Board/noAnswer/ok[snippets='http-request']

==== 성공

operation::Board/noAnswer/ok[snippets='http-response']

==== 실패

operation::Board/noAnswer/wrongToken[snippets='http-response']

=== 내 문의 전체 조회

operation::Board/myQuestions/ok[snippets='http-request']

==== 성공

operation::Board/myQuestions/ok[snippets='http-response']

==== 실패

operation::Board/myQuestions/wrongToken[snippets='http-response']

=== 보드 등록

operation::Board/saveBoard/ok[snippets='http-request']

==== 성공

operation::Board/saveBoard/ok[snippets='http-response']

==== 실패

operation::Board/saveBoard/wrongToken[snippets='http-response']

IMPORTANT: 잘못된 토큰

operation::Board/saveBoard/noContent[snippets='http-response']

IMPORTANT: 보드 내용 생략했을 때

operation::Board/saveBoard/noType[snippets='http-response']

IMPORTANT: 보드 타입 생략했을 때

=== 보드(faq, 공지사항) 전체 조회

operation::Board/getBoard/okAdmin[snippets='http-request']

==== 성공

operation::Board/getBoard/okAdmin[snippets='http-response']

IMPORTANT: ADMIN 일때

operation::Board/getBoard/okCommon[snippets='http-response']

IMPORTANT: COMMON 일때

==== 실패

operation::Board/getBoard/wrongToken[snippets='http-response']

=== 보드(terms, privacy) 조회

operation::Board/getBoardCreatedDate/okAdminFirst[snippets='http-request']

==== 성공

operation::Board/getBoardCreatedDate/okAdminFirst[snippets='http-response']

IMPORTANT: admin 최근 보드 조회

operation::Board/getBoardCreatedDate/okAdminSecond[snippets='http-response']

IMPORTANT: admin 직전 보드 조회

operation::Board/getBoardCreatedDate/okCommonFirst[snippets='http-response']

IMPORTANT: common 최근 보드 조회

operation::Board/getBoardCreatedDate/okCommonSecond[snippets='http-response']

IMPORTANT: common 직전 보드 조회

==== 실패

operation::Board/getBoardCreatedDate/thirdBoard[snippets='http-response']

IMPORTANT: 3번째 보드 조회

operation::Board/getBoardCreatedDate/noBoard[snippets='http-response']

IMPORTANT: 전체 보드 1개일 때 2번째 조회시

operation::Board/getBoardCreatedDate/wrongToken[snippets='http-response']

IMPORTANT: 잘못된 토큰

=== 답변 조회 (searchAnswer)

operation::Board/searchAnswer/ok[snippets='http-request,request-parameters']

==== 성공

operation::Board/searchAnswer/ok[snippets='http-response']
