=== 문의 등록

operation::Board/Save/okOneToOne[snippets='http-request,request-fields']

==== 성공

operation::Board/Save/okOneToOne[snippets='http-response']

IMPORTANT: 로그인 하고 요청

operation::Board/Save/okLogin[snippets='http-response']

IMPORTANT: 로그인 안하고 요청

==== 실패

operation::Board/Save/wrongToken[snippets='http-response']

IMPORTANT: 연락처가 없을 때

operation::Board/Save/wrongToken[snippets='http-response']

IMPORTANT: 토큰이 잘못되었을 때

=== 문의 전체 조회

operation::Board/GetInquiries/ok[snippets='http-request']

==== 성공

operation::Board/GetInquiries/ok[snippets='http-response']

=== 선택

operation::Board/select/ok[snippets='http-request,path-parameters']

==== 성공

operation::Board/select/ok[snippets='http-response']

==== 실패

operation::Board/select/wrongSelect[snippets='http-response']

IMPORTANT: 잘못된 문의 선택 조회

operation::Board/select/wrongSelect[snippets='http-response']

IMPORTANT: 토큰이 잘못됨

=== 답변 등록

operation::Board/answer/okOneToOneAnswer[snippets='http-request']

==== 성공

operation::Board/answer/okOneToOneAnswer[snippets='http-response']

IMPORTANT: 1:1 문의 상황일 때

operation::Board/answer/okLoginAnswer[snippets='http-response']

IMPORTANT: 로그인 문의 상황일 때

==== 실패

operation::Board/answer/noContent[snippets='http-response']

IMPORTANT: 답변 내용이 없을 때

operation::Board/answer/wrongToken[snippets='http-response']

IMPORTANT: 토큰이 잘못됨

=== 답변 되지 않은 문의 조회

operation::Board/noAnswer/ok[snippets='http-request']

==== 성공

operation::Board/noAnswer/ok[snippets='http-response']

==== 실패

operation::Board/noAnswer/wrongToken[snippets='http-response']