=== 라벨 생성 (register)

operation::Label/register/ok[snippets='http-request,request-fields']

==== 성공

operation::Label/register/ok[snippets='http-response']

==== 실패

operation::Label/register/noLabelName[snippets='http-response']

IMPORTANT: 라벨의 이름이 없을 때

operation::Label/register/noOwner[snippets='http-response']

IMPORTANT: 라벨의 소유자가 없을 때

operation::Label/register/noFile[snippets='http-response']

IMPORTANT: 라벨을 등록할 파일이 없을 때

operation::Label/register/wrongToken[snippets='http-response']

IMPORTANT: 토큰이 잘못됐을 때

=== 라벨 영구 제거 (deregister)

operation::Label/deregister/ok[snippets='http-request']

==== 성공

operation::Label/deregister/ok[snippets='http-response']

==== 실패

operation::Label/deregister/wrongToken[snippets='http-response']

=== 라벨 제거 (remove)

operation::Label/remove/ok[snippets='http-request']

==== 성공

operation::Label/remove/ok[snippets='http-response']

==== 실패

operation::Label/remove/wrongToken[snippets='http-response']

=== 라벨 붙이기 (attach)

operation::Label/attach/ok[snippets='http-request']

==== 성공

operation::Label/attach/ok[snippets='http-response']

==== 실패

operation::Label/attach/noLabelName[snippets='http-response']

IMPORTANT: 라벨의 이름이 없을 때

operation::Label/attach/noOwner[snippets='http-response']

IMPORTANT: 라벨의 소유자가 없을 때

operation::Label/attach/noFile[snippets='http-response']

IMPORTANT: 라벨을 등록할 파일이 없을 때

operation::Label/attach/wrongToken[snippets='http-response']

IMPORTANT: 토큰이 잘못됐을 때

=== 라벨 검색 (search)

operation::Label/search/ok[snippets='http-request']

==== 성공

operation::Label/search/ok[snippets='http-response']

==== 실패

operation::Label/search/wrongToken[snippets='http-response']