=== 삭제 (delete)

operation::User/Delete/ok[snippets='http-request,path-parameters']

==== 성공

operation::User/Delete/ok[snippets='http-response']

==== 실패

operation::User/Delete/wrongFormat[snippets='http-response']

IMPORTANT: 아이디가 너무 길 때

operation::User/Delete/notFindUser[snippets='http-response']

IMPORTANT: 등록되지 않은 유저일 때

operation::User/Delete/unauthorized[snippets='http-response']

IMPORTANT: 권한이 없을 때

=== 등록 (register)

operation::User/Register/ok[snippets='http-request,request-fields']

==== 성공

operation::User/Register/ok[snippets='http-response']

==== 실패

operation::User/Register/unauthorized[snippets='http-response']

IMPORTANT: 권한이 없을 때

operation::User/Register/wrongFormat[snippets='http-response']

IMPORTANT: payload가 올바르지 않을 때

operation::User/Register/duplicated[snippets='http-response']

IMPORTANT: 중복된 유저 등록

=== 프로필 업데이트 (update)

operation::User/Update/ok[snippets='http-request,request-fields,path-parameters']

==== 성공

operation::User/Update/ok[snippets='http-response']

==== 실패

operation::User/Update/unauthorized[snippets='http-response']

IMPORTANT: 권한이 없을 때

operation::User/Update/wrongFormat[snippets='http-response']

IMPORTANT: payload가 올바르지 않을 때

operation::User/Update/notFoundUser[snippets='http-response']

IMPORTANT: 유저를 찾을 수 없을 때

operation::User/Update/duplicatedName[snippets='http-response']

IMPORTANT: 중복된 유저 등록

=== 프로필 조회 (profile)

operation::User/Profile/ok[snippets='http-request,path-parameters']

==== 성공

operation::User/Profile/ok[snippets='http-response']

==== 실패

operation::User/Profile/unauthorized[snippets='http-response']

IMPORTANT: 권한이 없을 때

operation::User/Profile/notFoundUser[snippets='http-response']

IMPORTANT: 유저를 찾을 수 없을 때

operation::User/Profile/wrongFormat[snippets='http-response']

IMPORTANT: payload가 올바르지 않을 때

=== 유저 검색 (search)

operation::User/Search/ok[snippets='http-request,request-parameters']

==== 성공

operation::User/Search/ok[snippets='http-response']
